-- CREATE TABLES FOR AUTHENTICATION AND AUTHORIZATION

-- drop schema if exists public cascade;
-- create schema if not exists public;

CREATE TABLE sec_user (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usr_login VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP DEFAULT NOW(),
    atualizado_em TIMESTAMP DEFAULT NOW(),
    senha_reset_token VARCHAR(255) NULL,
    ativo BOOLEAN DEFAULT TRUE
);

CREATE TABLE sec_perfil (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL
);


CREATE TABLE sec_user_perfil (
    user_id BIGINT NOT NULL,
    perfil_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, perfil_id),
    FOREIGN KEY (user_id) REFERENCES sec_user(id),
    FOREIGN KEY (perfil_id) REFERENCES sec_perfil(id)
);

Create TABLE sec_permission (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255)
);

Create  TABLE sec_perfil_permission (
    perfil_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (perfil_id, permission_id),
    FOREIGN KEY (perfil_id) REFERENCES sec_perfil(id),
    FOREIGN KEY (permission_id) REFERENCES sec_permission(id)
);

Create table settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    setting_key VARCHAR(100) NOT NULL,
    setting_value VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP DEFAULT NOW(),
    atualizado_em TIMESTAMP DEFAULT NOW()
);

Create table app_log_action (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    action_code VARCHAR(255) NOT NULL UNIQUE,
    action_description TEXT NOT NULL
);

Create table app_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    action_code VARCHAR(255) NOT NULL ,
    action_details TEXT,
    action_timestamp TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES sec_user(id),
    FOREIGN KEY (action_code) REFERENCES app_log_action(action_code)
);




-- Initial data for startup enviornment
INSERT INTO sec_user (usr_login, senha, email) VALUES ('system', '$2y$10$kCToPYDY8lqLlYHguO6kR./3IPd3aKeFUmIDSPH6lejbzVWxtX5Ay', 'system');
INSERT INTO sec_user (usr_login, senha, email) VALUES ('admin', '$2y$10$kCToPYDY8lqLlYHguO6kR./3IPd3aKeFUmIDSPH6lejbzVWxtX5Ay', 'admin@admin.com');
INSERT INTO sec_user (usr_login, senha, email) VALUES ('user', '$2y$10$kCToPYDY8lqLlYHguO6kR./3IPd3aKeFUmIDSPH6lejbzVWxtX5Ay', 'user@user.com');

INSERT INTO sec_perfil (nome) VALUES ('SYSTEM');
INSERT INTO sec_perfil (nome) VALUES ('ADMIN');
INSERT INTO sec_perfil (nome) VALUES ('USER');

INSERT INTO sec_user_perfil (user_id, perfil_id) VALUES (1, 1);
INSERT INTO sec_user_perfil (user_id, perfil_id) VALUES (2, 2);
INSERT INTO sec_user_perfil (user_id, perfil_id) VALUES (3, 3);

INSERT INTO sec_permission (nome, descricao) VALUES ('READ_PRIVILEGES', 'Permission to read data');
INSERT INTO sec_permission (nome, descricao) VALUES ('WRITE_PRIVILEGES', 'Permission to write data');

INSERT INTO sec_perfil_permission (perfil_id, permission_id) VALUES (1, 1);
INSERT INTO sec_perfil_permission (perfil_id, permission_id) VALUES (1, 2);
INSERT INTO sec_perfil_permission (perfil_id, permission_id) VALUES (2, 1);
INSERT INTO sec_perfil_permission (perfil_id, permission_id) VALUES (2, 2);
INSERT INTO sec_perfil_permission (perfil_id, permission_id) VALUES (3, 1);

INSERT INTO settings (setting_key, setting_value) VALUES ('DEFAULT_USER_PROFILE', 'USER');

INSERT INTO app_log_action (action_code, action_description) values ('INIT_APPLICATION', 'Initialization with default settings and users');

INSERT INTO app_log (user_id, action_code, action_details) VALUES (1, 'INIT_APPLICATION', 'Startup initialization of the application with default users, profiles, and permissions.');
