CREATE TABLE sec_user (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    criado_em TIMESTAMP DEFAULT NOW()
);

CREATE TABLE sec_perfil (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL
);


CREATE TABLE sec_user_perfil (
    user_id BIGINT NOT NULL,
    perfil_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, perfil_id),
    FOREIGN KEY (user_id) REFERENCES sec_user(id),
    FOREIGN KEY (perfil_id) REFERENCES sec_perfil(id)
);

Create TABLE sec_permission (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255)
);

Create  TABLE sec_perfil_permission (
    perfil_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (perfil_id, permission_id),
    FOREIGN KEY (perfil_id) REFERENCES sec_perfil(id),
    FOREIGN KEY (permission_id) REFERENCES sec_permission(id)
);

Create table sec_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    action VARCHAR(255) NOT NULL,
    action_details TEXT,
    timestamp TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES sec_user(id)
);
